### ISSUE TITLE
incorect folder

### ISSUE THREAD

**Issue by Lord9120** [MisterJ936/Explorer-Context-Menu-Integration-for-windows-terminal#1]
terminal folder have to be in bat folder where is install.bat and uninstall.bat, if not they won't be a icon in context menu

**Comment by JenuelDev** [comment]
get the source code here:
https://github.com/MisterJ936/Explorer-Context-Menu-Integration-for-windows-terminal/releases

extract in a new folder or directory.
Click Install to configure things for you.
Click Uninstall to remove registry on your registry.
![Screenshot 2020-09-20 122708](https://user-images.githubusercontent.com/31676163/93694307-9f73d700-fb3c-11ea-95b7-9690245cb26e.png)
