### ISSUE TITLE
Consider deprecating repository and/or consider fixing launching

### ISSUE THREAD

**Issue by patricknelson** [MisterJ936/Explorer-Context-Menu-Integration-for-windows-terminal#5]
It appears that the latest version of Windows Terminal now automatically supports opening via explorer shell integration _with_ working directory support (and from what I can tell, bug free). e.g. See: https://github.com/microsoft/terminal/issues/8933 

That said: The reason I even noticed was because the app updated itself in the background and right-click integration (manually enabled via these scripts) stopped working since the launch path of `C:\Users\USERNAME\AppData\Local\Microsoft\WindowsApps\wt.exe` was no longer working for me. So, I'd propose maybe:

1. Documenting that the functionality available in this repository is probably no longer useful for versions `1.9.x` and above
2. Potentially even archiving this repository (assuming you don't want to maintain backward compatibility for older versions of Windows Terminal, assuming it's even possible to install prior versions)
3. If not archiving, fix launching of the app. Not sure how this'd be accomplished, since the only path that'd work in _my case_ is `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.9.1942.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe` which I assume may vary between either people or versions of the app (not sure).

What do you think?

**Comment by JenuelDev** [comment]
I guess we will mark this repository as deprecated. It seems that the windows terminal context menu is now built in the core of their installation process. I will be archiving the repository as well.

**Comment by patricknelson** [comment]
Alright. And thanks again for building this! I found it incredibly useful and used it daily (since what they had before was either nonexistent or broken).

**Comment by JenuelDev** [comment]
> Alright. And thanks again for building this! I found it incredibly useful and used it daily (since what they had before was either nonexistent or broken).

thanks for being a part of this simple project, man :)
